### ISSUE TITLE
New Proposal Component - Card List Layout

### ISSUE THREAD

**Issue by rayyan-innovation** [pegasystems/constellation-ui-gallery#109]
# Card List Layout Component

A flexible and responsive card list layout component for displaying data in a grid format with customizable styling and interactive features.

## Features

- Responsive grid layout that adapts to screen size
- Configurable number of columns
- Optional header with breadcrumb navigation
- Customizable card styling with hover effects
- Support for icons and custom headers
- Built-in request history viewing functionality
- RTL/LTR layout support
- Light/Dark mode theming
- Integration with PCore data management

## Key Properties

- `NumCols`: Number of columns to display in the grid
- `header`: Title text for the component
- `link`: URL property for clickable cards
- `isIcon`: Toggle icon display
- `isHeader`: Toggle header section display
- `pageTitle`: Title for the header section
- `iconName`: Name of the icon to display (supports 'faDatabase' and 'faMobileScreenButton')

## Dependencies

The component requires:
- @fortawesome/free-solid-svg-icons
- @fortawesome/react-fontawesome
- @material-ui/core
- @pega/cosmos-react-core
- React

## Theme Customization

Includes a comprehensive theming system with:
- Color schemes
- Spacing configurations
- Border radius presets
- Responsive breakpoints

## Usage Example

```tsx
<InnovationTeamComponentLibCardListLayout
  NumCols={3}
  header="Services"
  isIcon={true}
  isHeader={true}
  pageTitle="Digital Services"
  iconName="faDatabase"
  link="url"
/>
```

## Attachments

[CardListLayout.zip](https://github.com/user-attachments/files/18050834/CardListLayout.zip)

**Comment by ricmars** [comment]
Request for new component rejected: there is already a card gallery example - also the component uses libraries that are not accepted (material and fortawesome) - Only the Constellation component library should be used (@pega/cosmos-react-xxx)

**Comment by rayyan-innovation** [comment]
Hello @ricmars 
I have updated the attachment to follow the best practices guidance. Please re-review

**Comment by ricmars** [comment]
the code is not compiling - Box or Card.Header does not exist in Cosmos-core - Also code in the Header folder is still using Material UI - I am not sure what is the benefit of this component instead of using https://pegasystems.github.io/constellation-ui-gallery/?path=/docs/widgets-card-gallery--docs - there are several issues with this code including hardcoded default image, view names for localization 
<img width="598" alt="Screenshot 2024-12-30 at 1 34 26 PM" src="https://github.com/user-attachments/assets/c7f9492a-9cf1-4c40-a046-068677ffd7cc" />

Don't invest more time trying to fix this component - You can use it internally but it will not benefit other users.
