### ISSUE TITLE
Gantt chart component

### ISSUE THREAD

**Issue by ricmars** [pegasystems/constellation-ui-gallery#15]
The goal is to represent a list of data objects in a Gantt chart along with there dependencies. The objects could be cases or data objects.

**Comment by vijayjangid** [comment]
I am looking into this, exploring open source libraries like https://www.npmjs.com/package/vis-react

**Comment by vijayjangid** [comment]
These some of the open source libraries I found in a quick scan. Will do a comparative study and share Pros/cons.
At first glance, none of these is keyboard accessible. Only a few supports dependency within Gantt.

1. https://www.npmjs.com/package/vis-react
2. https://github.com/neuronetio/gantt-schedule-timeline-calendar
3. https://github.com/ANovokmet/svelte-gantt
4. https://github.com/TheTechCompany/react-timeline-gantt
5. https://github.com/medesd/react-gantt

**Comment by vijayjangid** [comment]
Here is the comparision of different libraries shared above. These are sorted in the order of best to worst fit for our requirement.

| Rank | Library | Demo | Framework | Typescript | Keyboard navigation | Comment
|:---:|---|---|---|:---:|:---:|---|
| 🥇 | [gantt-task-react](https://github.com/MaTeMaTuK/gantt-task-react) | [Gantt schedule](https://matematuk.github.io/gantt-task-react/) | React | ✅   | 🔲  (partial support) | Tasks are keyboard focusable but connectors are not. UX is good.  I like this one the most fit |
| 🥈  | [svelte-gantt](https://github.com/ANovokmet/svelte-gantt) | [Gantt](https://anovokmet.github.io/svelte-gantt) | svelte (can be used in React code) | ✅   | ❌ | Supports Gantt with dependencies |
| 🥉  | [react-timeline-gantt](https://github.com/TheTechCompany/react-timeline-gantt) | [Timeline Gantt](https://thetechcompany.github.io/react-timeline-gantt/) | React | ✅   | ❌ | UX is not very intuitive. Depencies feature is not consistantly working |
| - | [react-gantt](https://github.com/neuronetio/gantt-schedule-timeline-calendar) | [Gantt](https://codesandbox.io/s/github/MEDESD/react-gantt) | React | ✅   | ❌ | Very basic, doesn't have dependencies feature support |
| - | [vis-react](https://github.com/anishmprasad/vis-react) | [Timeline](https://visjs.github.io/vis-timeline/examples/timeline/) | JS | ❌  | ❌ | This doesn't have a Gantt chart componenet directly. Timeline component could be used with some tweaks but UX will be a challenge. Not updated since last 4 years |
|-| [neuronetio-gantt](https://github.com/neuronetio/gantt-schedule-timeline-calendar) | [Gantt schedule](https://gantt-schedule-timeline-calendar.neuronet.io/) | React | ✅   | ❌ | **PAID** library - cannot use |

**Comment by ricmars** [comment]
great analysis and details - gantt-task-react looks a great choice
